//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PXWeb
{


    public partial class TableList
    {

        /// <summary>
        /// UserManualMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PXWeb.CustomControls.UserManualScreenReader UserManualMenu;

        /// <summary>
        /// MenuExplanation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PXWeb.UserControls.MenuExplanation MenuExplanation;

        /// <summary>
        /// MenuTableList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel MenuTableList;

        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new PXWeb.PxWeb Master
        {
            get
            {
                return ((PXWeb.PxWeb)(base.Master));
            }
        }
    }
}
