name: MSBuild

on: push

permissions:
  contents: read
  
jobs:
  build:

    runs-on: windows-2022

    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:

    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0

    - uses: NuGet/setup-nuget@323ab0502cd38fdc493335025a96c8fdb0edc71f # v2.0.1

    - name: Restore NuGet packages
      run: nuget restore PCAxis.PX-Web.sln

    - name: Build the application
      run: msbuild /p:Configuration=$env:Configuration  PCAxis.PX-Web.sln
      env:
        Configuration: ${{ matrix.configuration }}
        
    #- name: Create a file
    #  run: echo "I won't live long" > my_file.txt

    #- name: Upload Artifact
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: my-own-artifact
    #    path: my_file.txt
    #    retention-days: 5
